import { hostedUrl, profile } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: `Muhammed Sinan | Full Stack Developer | MERN Stack Expert`,
        template: "%s | Muhammed Sinan",
    },
    description: "Full Stack Developer specializing in MERN stack. Building scalable web applications with React, Node.js, Express, MongoDB, and Next.js. Available for collaboration.",
    keywords: [
        "sinanptm",
        "Sinan Muhammed",
        "Muhammed Sinan Portfolio",
        "Full Stack Developer",
        "MERN Stack Expert",
        "React Developer",
        "Node.js Developer",
        "Web Developer India",
        "Mern stack Developer Kerala",
        "Freelance Developer Kerala",
        "Backend Developer",
        "Frontend Developer",
        "Next.js Developer",
        "Web Applications Expert",
        "E-commerce Developer",
        "Software Engineer Portfolio",
        "Responsive Web Design",
        "UI/UX Developer",
        "Open Source Contributor",
        "Creative Developer",
        "Digital Transformation Specialist",
        "Muhammed Sinan Tech Portfolio",
        "Kerala Software Developer",
        "Scalable Web Applications",
        "Freelance Web Developer",
        "Innovative Web Solutions",
        "Kozhikode Full Stack Developer",
        "Global Web Developer",
        "MERN Stack Projects",
        "Interactive Web Design",
        "Tech Innovator India",
        "Portfolio Web Developer",
        "Cloud-Ready Applications Developer",
        "Custom Web Solutions",
        "sinanptm Professional Portfolio",
        "Web Design and Development",
        "Modern UI/UX Developer",
        "Muhammed Sinan Software Engineer",
        "API Development Specialist",
        "Web Development Trends",
        "Enterprise Web Developer",
        "Tech Solutions Innovator",
        "Developer Portfolio Showcase",
        "Freelance Tech Expert",
        "Web Development Specialist",
        "Cutting-Edge Web Developer",
        "India Web Developer Portfolio",
        "Cross-Platform Development",
        "Advanced Web Applications",
        "Muhammed Sinan Developer Projects",
        "Dynamic Web Solutions",
        "Tech Projects Portfolio",
        "Software Engineering Expert",
        "Full Stack Specialist",
        "Remote Web Developer",
    ],    
        authors: [
        {
            name: "Muhammed Sinan",
            url: "https://github.com/sinanptm",
        }
    ],
    creator: "Muhammed Sinan (sinanptm)",
    publisher: "sinanptm",
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    applicationName: "sinanptm Portfolio",
    generator: "Next.js",
    referrer: "origin-when-cross-origin",
    openGraph: {
        type: "website",
        locale: "en_US",
        url: hostedUrl,
        siteName: "sinanptm Portfolio",
        title: `${profile.name} | ${profile.title}`,
        description: "Full Stack Developer specializing in MERN stack development. Building scalable web applications with React, Node.js, Express, MongoDB, and Next.js.",
        images: [
            {
                url: "/screenshots/og-image.jpg",
                width: 1200,
                height: 630,
                alt: "Muhammed Sinan - Full Stack Developer Portfolio",
                type: "image/png",
            }
        ],
        countryName: "India",
    },
    appleWebApp: {
        capable: true,
        title: "Sinan ptm Portfolio",
        statusBarStyle: "black-translucent",
    },
    verification: {
        google: "google815b889e8dec9b27", 
    },
    twitter: {
        card: "summary_large_image",
        title: `${profile.name} | ${profile.title}`,
        description: "Full Stack Developer specializing in MERN stack development. Building scalable web applications with React, Node.js, Express, MongoDB, and Next.js.",
        images: ["/screenshots/twitter-image.png"],
        creator: `@${profile.xUserName}`,
        site: `@${profile.xUserName}`,
    },
    robots: {
        index: true,
        follow: true,
        nocache: true,
        googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
        },
    },
    icons: {
        icon: [
            { url: "/icons/favicon.ico" },
            { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
            { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
            { url: "/icons/favicon-96x96.png", sizes: "96x96", type: "image/png" },
        ],
        apple: [
            { url: "/icons/apple-icon-57x57.png", sizes: "57x57", type: "image/png" },
            { url: "/icons/apple-icon-60x60.png", sizes: "60x60", type: "image/png" },
            { url: "/icons/apple-icon-72x72.png", sizes: "72x72", type: "image/png" },
            { url: "/icons/apple-icon-76x76.png", sizes: "76x76", type: "image/png" },
            { url: "/icons/apple-icon-114x114.png", sizes: "114x114", type: "image/png" },
            { url: "/icons/apple-icon-120x120.png", sizes: "120x120", type: "image/png" },
            { url: "/icons/apple-icon-144x144.png", sizes: "144x144", type: "image/png" },
            { url: "/icons/apple-icon-152x152.png", sizes: "152x152", type: "image/png" },
            { url: "/icons/apple-icon-180x180.png", sizes: "180x180", type: "image/png" },
        ],
        shortcut: ["/icons/favicon.ico"]
    },
    manifest: "/manifest.json",
    alternates: {
        canonical: hostedUrl,
        languages: {
            "en-US": hostedUrl,
        },
    },
    category: "technology",
    classification: "Portfolio Website",
    metadataBase: new URL(hostedUrl),
    assets: '/assets'
};

export default metadata;