import { hostedUrl, profile } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: `Muhammed Sinan | Full Stack Developer | MERN Stack Expert`,
        template: "%s | Muhammed Sinan",
    },
    description: "Full Stack Developer specializing in MERN stack. Building scalable web applications with React, Node.js, Express, MongoDB, and Next.js. Available for collaboration.",
    keywords: [
        "Muhammed sinan ptm",
        "Muhammed Sinan",
        "sinan ptm",
        "sinanptm",
        "sinan",
        "ptm",
        "Full Stack Developer",
        "Sinanptm portfolio",
        "MERN Stack",
        "React Developer",
        "Node.js Developer",
        "Web Developer",
        "Software Engineer",
        "Portfolio",
        "Full Stack Engineer",
        "Web Applications",
        "Frontend Development",
        "Backend Development",
        "Database Design",
        "Cloud Computing",
        "REST API",
        "Responsive Design",
        "UI/UX Development",
        "portfolio template",
        "Personal Portfolio",
        "Web Developer Portfolio",
        "Full Stack Developer Portfolio",
        "React Developer Portfolio",
        "MERN Stack Portfolio",
        "Web Applications Portfolio",
        "Software Engineering Portfolio",
        "Tech Portfolio",
        "Showcase Portfolio",
        "Developer Projects Portfolio",
        "Frontend & Backend Developer Portfolio",
        "Responsive Portfolio Design",
        "Interactive Portfolio",
        "UX/UI Portfolio",
        "Creative Portfolio",
        "Nextjs portfolio",
        "3d portfolio",
        "animated portfolio",
        "GitHub Projects Portfolio",
        "Tech Showcase Portfolio",
    ],
    authors: [
        {
            name: "Muhammed Sinan",
            url: "https://github.com/sinanptm",
        }
    ],
    creator: "Muhammed Sinan (sinanptm)",
    publisher: "sinanptm",
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    applicationName: "sinanptm Portfolio",
    generator: "Next.js",
    referrer: "origin-when-cross-origin",
    openGraph: {
        type: "website",
        locale: "en_US",
        url: hostedUrl,
        siteName: "sinanptm Portfolio",
        title: `${profile.name} | ${profile.title}`,
        description: "Full Stack Developer specializing in MERN stack development. Building scalable web applications with React, Node.js, Express, MongoDB, and Next.js.",
        images: [
            {
                url: "/screenshots/og-image.png",
                width: 1200,
                height: 630,
                alt: "Muhammed Sinan - Full Stack Developer Portfolio",
                type: "image/png",
            }
        ],
        countryName: "India",
    },
    twitter: {
        card: "summary_large_image",
        title: `${profile.name} | ${profile.title}`,
        description: "Full Stack Developer specializing in MERN stack development. Building scalable web applications with React, Node.js, Express, MongoDB, and Next.js.",
        images: ["/screenshots/twitter-image.png"],
        creator: `@${profile.xUserName}`,
        site: `@${profile.xUserName}`,
    },
    robots: {
        index: true,
        follow: true,
        nocache: true,
        googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
        },
    },
    icons: {
        icon: [
            { url: "/icons/favicon.ico" },
            { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
            { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
            { url: "/icons/favicon-96x96.png", sizes: "96x96", type: "image/png" },
        ],
        apple: [
            { url: "/icons/apple-icon-57x57.png", sizes: "57x57", type: "image/png" },
            { url: "/icons/apple-icon-60x60.png", sizes: "60x60", type: "image/png" },
            { url: "/icons/apple-icon-72x72.png", sizes: "72x72", type: "image/png" },
            { url: "/icons/apple-icon-76x76.png", sizes: "76x76", type: "image/png" },
            { url: "/icons/apple-icon-114x114.png", sizes: "114x114", type: "image/png" },
            { url: "/icons/apple-icon-120x120.png", sizes: "120x120", type: "image/png" },
            { url: "/icons/apple-icon-144x144.png", sizes: "144x144", type: "image/png" },
            { url: "/icons/apple-icon-152x152.png", sizes: "152x152", type: "image/png" },
            { url: "/icons/apple-icon-180x180.png", sizes: "180x180", type: "image/png" },
        ],
        shortcut: ["/icons/favicon.ico"]
    },
    manifest: "/manifest.json",
    alternates: {
        canonical: hostedUrl,
        languages: {
            "en-US": hostedUrl,
        },
    },
    category: "technology",
    classification: "Portfolio Website",
    metadataBase: new URL(hostedUrl),
    assets: '/assets'
};

export default metadata;